#!/bin/bash
set -ueo pipefail

if [[ "$#" -ne 1 ]]; then
	echo
	echo 'usage: pw-dewire filename'
	echo
	exit 0
fi

while IFS= read -r line; do
	row0=$(echo "$line" | cut -d, -f1 | cut -d"'" -f2)
	row1=$(echo "$line" | cut -d, -f2 | cut -d"'" -f2)
	echo "Unloading:  ${row0}  -->  ${row1} ..."
	pw-link -d "$row0" "$row1" || true
done < <(cat "$1")
